AWSTemplateFormatVersion: '2010-09-09'
Description: Express Application running on AWS Lambda

Resources:
  ExpressApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./
      Timeout: 30
      MemorySize: 512
      Events:
        ProxyRoute:              # Catch-all for other routes
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: development
          STAGE: !Ref Stage
